name: Python Tests

on: 
  push:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        java: [ '8', '11', '17', '21' ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.4

    - name: Setup java
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java }}
        cache: 'maven'
        cache-dependency-path: ./pom.xml

    - name: Run tests
      run: java tests/HelloWorldApp.java
